version: 0.2
        
phases:
  install:
    runtime-versions:
      dotnet: 3.1
      nodejs: 12
      python: 3.8
    commands:
      - echo "Installing yarn"
      - curl -o- -L https://yarnpkg.com/install.sh | bash
      - echo "Installing the AWS CDK"
      - npm install -g aws-cdk
      - echo "Installing PowerShell"
      - wget -q https://packages.microsoft.com/config/ubuntu/18.04/packages-microsoft-prod.deb
      - dpkg -i packages-microsoft-prod.deb
      - apt-get update
      - add-apt-repository universe
      - apt-get install -y powershell
      - echo "Installing the Lambda CLI plugin"
      - dotnet new -i Amazon.Lambda.Templates
  build:
    commands:
      - yarn
      - yarn run release
reports:
  'arn:aws:codebuild:us-east-2:667342691845:report-group/hercules-dotnet-client-tests':
    files:
      - test-reports/Hercules.Api.Client/test-results.xml
    base-directory: location
    discard-paths: yes
    file-format: JunitXml
  'arn:aws:codebuild:us-east-2:667342691845:report-group/hercules-dotnet-client-coverage':
    files:
      - test-reports/Hercules.Api.Client/coverage.xml
    base-directory: location
    discard-paths: yes
    file-format: CoberturaXml
  'arn:aws:codebuild:us-east-2:667342691845:report-group/hercules-api-model-tests':
    files:
      - test-reports/Hercules.Api.Model/test-results.xml
    base-directory: location
    discard-paths: yes
    file-format: JunitXml
  'arn:aws:codebuild:us-east-2:667342691845:report-group/hercules-api-model-coverage':
    files:
      - test-reports/Hercules.Api.Model/coverage.xml
    base-directory: location
    discard-paths: yes
    file-format: CoberturaXml
artifacts:
  files:
    - packages/infrastructure/build
  discard-paths: yes