version: 0.2
        
phases:
  install:
    runtime-versions:
      dotnet: 3.1
      nodejs: 12
      python: 3.8
    commands:
      - echo "Installing yarn"
      - curl -o- -L https://yarnpkg.com/install.sh | bash
      - echo "Installing the AWS CDK"
      - npm install -g aws-cdk
      - echo "Installing the Lambda CLI plugin"
      - dotnet tool install -g Amazon.Lambda.Tools
  pre_build:
    commands:
      - aws codeartifact login --tool npm --repository chessdb-npm --domain chessdb --domain-owner 407299974961
  build:
    commands:
      - yarn
      - yarn run release
reports:
  'arn:aws:codebuild:us-east-2:667342691845:report-group/hercules-dotnet-client-tests':
    files:
      - test-reports/Hercules.Api.Client/test-results.xml
    base-directory: location
    discard-paths: yes
    file-format: JunitXml
  'arn:aws:codebuild:us-east-2:667342691845:report-group/hercules-dotnet-client-coverage':
    files:
      - test-reports/Hercules.Api.Client/coverage.xml
    base-directory: location
    discard-paths: yes
    file-format: CoberturaXml
  'arn:aws:codebuild:us-east-2:667342691845:report-group/hercules-api-model-tests':
    files:
      - test-reports/Hercules.Api.Model/test-results.xml
    base-directory: location
    discard-paths: yes
    file-format: JunitXml
  'arn:aws:codebuild:us-east-2:667342691845:report-group/hercules-api-model-coverage':
    files:
      - test-reports/Hercules.Api.Model/coverage.xml
    base-directory: location
    discard-paths: yes
    file-format: CoberturaXml
artifacts:
  files:
    - packages/infrastructure/build
  discard-paths: yes