version: 0.2
        
phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      - echo "Installing the AWS CDK"
      - npm install -g aws-cdk
  pre_build:
    commands:
      - TEMP_ROLE=`aws sts assume-role --role-arn $ASSUME_ROLE_ARN --role-session-name test`
      - export TEMP_ROLE
      - echo $TEMP_ROLE
      - export AWS_ACCESS_KEY_ID=$(echo "${TEMP_ROLE}" | jq -r '.Credentials.AccessKeyId')
      - export AWS_SECRET_ACCESS_KEY=$(echo "${TEMP_ROLE}" | jq -r '.Credentials.SecretAccessKey')
      - export AWS_SESSION_TOKEN=$(echo "${TEMP_ROLE}" | jq -r '.Credentials.SessionToken')
  build:
    commands:
      - npm i
      - npm run release
reports:
  'arn:aws:codebuild:us-east-2:667342691845:report-group/hercules-dotnet-client-tests':
    files:
      - test-reports/Hercules.Api.Client/test-results.xml
    base-directory: location
    discard-paths: yes
    file-format: JunitXml
  'arn:aws:codebuild:us-east-2:667342691845:report-group/hercules-dotnet-client-coverage':
    files:
      - test-reports/Hercules.Api.Client/coverage.xml
    base-directory: location
    discard-paths: yes
    file-format: CoberturaXml
  'arn:aws:codebuild:us-east-2:667342691845:report-group/hercules-api-model-tests':
    files:
      - test-reports/Hercules.Api.Model/test-results.xml
    base-directory: location
    discard-paths: yes
    file-format: JunitXml
  'arn:aws:codebuild:us-east-2:667342691845:report-group/hercules-api-model-coverage':
    files:
      - test-reports/Hercules.Api.Model/coverage.xml
    base-directory: location
    discard-paths: yes
    file-format: CoberturaXml
  'arn:aws:codebuild:us-east-2:667342691845:report-group/hercules-typescript-client-tests':
    files:
      - test-reports/api-client-typescript/test-results.xml
    base-directory: location
    discard-paths: yes
    file-format: JunitXml
  'arn:aws:codebuild:us-east-2:667342691845:report-group/hercules-typescript-client-coverage':
    files:
      - test-reports/api-client-typescript/coverage.xml
    base-directory: location
    discard-paths: yes
    file-format: CloverXml
  'arn:aws:codebuild:us-east-2:667342691845:report-group/aws-ts-client-core-tests':
    files:
      - test-reports/aws-api-client-core/test-results.xml
    base-directory: location
    discard-paths: yes
    file-format: JunitXml
  'arn:aws:codebuild:us-east-2:667342691845:report-group/aws-ts-client-core-coverage':
    files:
      - test-reports/aws-api-client-core/coverage.xml
    base-directory: location
    discard-paths: yes
    file-format: CloverXml
artifacts:
  files:
    - packages/infrastructure/build
  discard-paths: yes