version: 0.2
        
phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      - echo "Installing the AWS CDK"
      - npm install -g aws-cdk
  pre_build:
    commands:
      - TEMP_ROLE=`aws sts assume-role --role-arn $ASSUME_ROLE_ARN --role-session-name test`
      - export TEMP_ROLE
      - echo $TEMP_ROLE
      - export AWS_ACCESS_KEY_ID=$(echo "${TEMP_ROLE}" | jq -r '.Credentials.AccessKeyId')
      - export AWS_SECRET_ACCESS_KEY=$(echo "${TEMP_ROLE}" | jq -r '.Credentials.SecretAccessKey')
      - export AWS_SESSION_TOKEN=$(echo "${TEMP_ROLE}" | jq -r '.Credentials.SessionToken')
      - cdk deploy --app "$CODEBUILD_SRC_DIR" PipelinePlumber
  build:
    commands:
      - npm i
      - npm run release